### ISSUE TITLE
Can not connect to panel

### ISSUE THREAD

**Issue by proasnet** [ParadoxAlarmInterface/pai#305] opened 2022-08-08 18:44 UTC
Hi Yozik, is not possible find the reason for problem with connection the last days?

In report, I found now this:
Detail: Container: 
    fields = Container: 
        data = b'RC\x00\x00\x10\xdc\x00\x00\x00H\x00\x00\x00\x00\x00\x00'... (truncated, total 66)
        value = Container: 
            po = Container: 
                command = 5
                status = Container: 
                    reserved = False
                    alarm_reporting_pending = False
                    Winload_connected = True
                    NeWare_connected = False
            packet_length = 67
            control = Container: 
                ram_access = False
            bus_address = 0
            address = 4316
            data = b'\x00\x00\x00H\x00\x00\x00\x00\x00\x00\x00\x00\x00H\x00\x00'... (truncated, total 60)
        offset1 = 0
        offset2 = 66
        length = 66
    checksum = b'1' (total 1)

Hardware: panel EVOHD, IP100
Config
`LOGGING_LEVEL_CONSOLE: 20
LOGGING_LEVEL_FILE: 40
CONNECTION_TYPE: IP
SERIAL_PORT: /dev/ttyUSB0
SERIAL_BAUD: 57600
IP_CONNECTION_HOST: 192.168.0.180
IP_CONNECTION_PORT: 10000
IP_CONNECTION_PASSWORD: paradox
KEEP_ALIVE_INTERVAL: 10
LIMITS:
  zone: auto
  user: 1-2
  door: ''
  pgm: 1-5
  partition: auto
  module: ''
  repeater: ''
  keypad: ''
  key-switch: ''
SYNC_TIME: true
SYNC_TIME_MIN_DRIFT: 120
PASSWORD: '2580'
MQTT_ENABLE: true
MQTT_HOST: core-mosquitto
MQTT_PORT: 1883
MQTT_KEEPALIVE: 60
MQTT_USERNAME: pai
MQTT_PASSWORD: Jirutka8011
MQTT_HOMEASSISTANT_AUTODISCOVERY_ENABLE: true
COMMAND_ALIAS:
  arm: partition all arm
  disarm: partition all disarm
MQTT_COMMAND_ALIAS:
  armed_home: arm_stay
  armed_night: arm_sleep
  armed_away: arm
  disarmed: disarm
HOMEASSISTANT_NOTIFICATIONS_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
HOMEASSISTANT_PUBLISH_PARTITION_PROPERTIES:
  - target_state
  - current_state
HOMEASSISTANT_PUBLISH_ZONE_PROPERTIES:
  - open
  - tamper
PUSHBULLET_CONTACTS: []
PUSHBULLET_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
PUSHOVER_BROADCAST_KEYS: []
SIGNAL_CONTACTS: []
SIGNAL_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
GSM_CONTACTS: []
GSM_EVENT_FILTERS:
  - live,alarm,-restore
  - live,trouble,-clock
  - live,tamper
IP_INTERFACE_ENABLE: false
IP_INTERFACE_PASSWORD: paradox
DUMMY_EVENT_FILTERS: []`
Your work is very good, I has not problem last months
Thank you very much

**Comment by yozik04** [comment] 2022-08-08 18:48
Stop opening new tickets. You have one open already. Use that for your problem. If we will be able to help you, we will.

**Comment by yozik04** [comment] 2022-08-08 18:48
Dupe of #284

**Closed by yozik04** 2022-08-08 18:48 UTC

**Comment by proasnet** [comment] 2022-08-08 18:51
Okay, thank you very much for your time and help.
