### ISSUE TITLE
Interface not working 

### ISSUE THREAD

**Issue by JINXz** [ParadoxAlarmInterface/pai#245] opened 2021-05-21 05:46 UTC
**Alarm system**
Magellan MG5050 via IP150

**Environment**
raspberrypi4-64
hassos 5.13
Home Assistant 2021.5.5

**Python version**

**Git branch**
Prod and Dev

**Describe the bug**
Interface just doesn't work

ERROR    - PAI.paradox.lib.handlers - No handler for message 5

**To Reproduce**

[keybase.txt](https://github.com/ParadoxAlarmInterface/pai/files/6520341/keybase.txt)

**Comment by yozik04** [comment] 2021-05-21 12:39
dupe of #242

**Closed by yozik04** 2021-05-21 12:39 UTC
