### ISSUE TITLE
Hourly restarting PAI

### ISSUE THREAD

**Issue by proasnet** [ParadoxAlarmInterface/pai#264] opened 2021-10-11 12:12 UTC
## Alarm system
EVOHD 7.31

## Environment
RPi

## Git branch
hassOS

## Describe the bug
I have a problem with permanently restarting a PAI, connecting to panel, working hour, two hour and restarting again without connection. After some days, PAI working, then after some hours restarts again...

## To Reproduce
Nothing.
But after lose connection between PAI ( if RPI lose power) and IP100, IP100 must be restarted by power cable, if not, PAI can not connect.

## Logs

[log.txt](https://github.com/ParadoxAlarmInterface/pai/files/7322249/log.txt)

**Comment by yozik04** [comment] 2022-08-08 19:29
Dupe of #264. Log just tells that connection to panel was lost. No other issues.

**Closed by yozik04** 2022-08-08 19:29 UTC
Labels: bug, to be confirmed
