### ISSUE TITLE
organize entities by index instead of by name

### ISSUE THREAD

**Issue by sproit** [ParadoxAlarmInterface/pai#367] opened 2023-05-31 15:21 UTC
In some usages it might make more sense to get PAI to publish to topics such as _paradox/states/zones/1/open_ instead of _paradox/states/zones/some_area_name/open_ as in a Paradox system the zone numbers are decoupled from physical inputs anyway and as such can easily be kept constant over the lifetime of an installation.

A concrete example is the case where the name of a zone changes because the use of the zone changes slightly (Anne's room becomes Bob's room) but the application listening and logging PAI via MQTT wants to keep the same history without too much trouble.

If the name would just be a property, this would be a trivial event to process for the client application.

I can see multiple points in the code where I could start refactoring, but it seems like a rather big architectural change; so, I'd rather ask about it first :) Feasible? Not recommended?

**Comment by yozik04** [comment] 2023-05-31 15:26
I had a feature request somewhere about it. But I would like to make that optional and not default. HomeAssistant with Auto Discovery is not the only platform that can be used with PAI. Some people use OpenHAB or Homebridge and there are a lot more available. It is not intuitive to have numbers in there when you have to manually configure all bindings yourself.

**Comment by sproit** [comment] 2023-05-31 17:57
Yes, fore sure it would be optional.
Would it be a lot of effort? If I find the time and get a little guidance I might give it a try.

**Comment by yozik04** [comment] 2024-03-30 21:21
Duplicate of #181. Will close this one.

**Closed by yozik04** 2024-03-30 21:21 UTC
Labels: enhancement
