### ISSUE TITLE
integration not work after Home Asistant update

### ISSUE THREAD

**Issue by danygi79** [ParadoxAlarmInterface/pai#244] opened 2021-05-20 22:26 UTC
## Alarm system
EVOHD

## Environment
- HASSIO over Proxmox

## Git branch
master

## Describe the bug
not work after upgrade home assitant from 2021.5.2 to 2021.5.3

## To Reproduce
no step, only home assistan update

[log.txt](https://github.com/ParadoxAlarmInterface/pai/files/6519021/log.txt)

**Comment by yozik04** [comment] 2021-05-21 12:38
dupe of #242

**Closed by yozik04** 2021-05-21 12:38 UTC
Labels: bug, to be confirmed
