### ISSUE TITLE
Connection Problem on MG5050 V.7.14.2 via IP150

### ISSUE THREAD

**Issue by jonny2091** [ParadoxAlarmInterface/pai#144] opened 2020-03-10 15:10 UTC
Alarm system
Magellan MG5050 V.7.14.2 access mode via IP150 V.4.42.004

 Environment
RPI3 Ubuntu 18.04.4 LTS
      Python version 3.6.9

 Git branch
 Which Git branch you use. Did you tried "dev" branch

 Question
Is direct connection via IP150 possible? I don't understand where the error is...
sorry, i'm newbie, i tried to look for similar errors but i didn't find anything about it

 Logs 
[errorrpi.txt](https://github.com/ParadoxAlarmInterface/pai/files/4313143/errorrpi.txt)

**Comment by jpbarraca** [comment] 2020-03-10 15:39
According to the log you are trying to use the Serial Port for connection. 
Please set the CONNECTION_TYPE to 'IP' and adjust the IP_CONNECTION_* settings.

As this is not a bug with PAI, we will close it. Please join our [gitter community](https://gitter.im/paradox-alarm-interface)  as this can be discussed there.

**Closed by jpbarraca** 2020-03-10 15:39 UTC
Labels: question
