### ISSUE TITLE
Latest PAI destroy Paradox panel clock

### ISSUE THREAD

**Issue by kovaccs** [ParadoxAlarmInterface/pai#186] opened 2020-10-27 13:31 UTC
I have a latest PAI installed as a Hass-io add-on, and I have been using it with satisfaction for months. Installed PAI: 2.2.3
My country is Hungary, and my Hass-io date is:
~ $ date
Tue Oct 27 13:32:28 CET 2020    (it's DST time)_

When I restart PAI add-on the Paradox wallpanel (TM-50) always show exactly one hour less then the real time.  Has it to do with winter time setting last weekend? Older releases didn't do this.

I appreciat any help.

**Comment by yozik04** [comment] 2020-10-27 13:34
Main or dev version? What panel?

**Comment by kovaccs** [comment] 2020-10-27 13:35
This not the Dev version!

**Comment by stosoorok** [comment] 2020-10-31 09:19
@kovaccs Do you have a right time zone configured with Babyware? No problems with EVO-HD and main PAI 2.2.3.

**Comment by kovaccs** [comment] 2020-10-31 11:28
> @kovaccs Do you have a right time zone configured with Babyware? No problems with EVO-HD and main PAI 2.2.3.

Yes! Certainly. First I checked in BabyWare the correct timezone and hours setting. They are corret until I start PAI. After that the hour decrement by 1. Always!

**Comment by yozik04** [comment] 2020-10-31 20:36
I can confirm it, but nothing changed in PAI's code for time sync. Looks like homeassistant plugins now receive timezone differently....

**Comment by kovaccs** [comment] 2020-11-01 12:16
"I'm sorry, but there's still a problem. It hasn’t been running on the PAI add-on for two days and the Paradox clock is really showing the right time."
It is possible. It hasn’t been running on the PAI add-on for two days and the Paradox clock is really showing the right time.
I upgraded to the published 2.2.4 today and after the PAI start the Paradox clock immediately showed 1 hour less.
This problem did not occur with older versions under 2.2.3 and I did not install newer HA add-ons. I have been using PAI almost since its publication without the clock setting error.
If I find an older version I will try to reinstall it.

**Comment by yozik04** [comment] 2020-11-01 12:33
Disable time sync for now.

**Comment by kovaccs** [comment] 2020-11-01 12:39
Sorry, how to do that?

**Comment by yozik04** [comment] 2020-11-01 13:19
SYNC_TIME: false

**Comment by kovaccs** [comment] 2020-11-01 14:04
Brrrrr! Let's say I could have found out for myself if I had looked more closely at the configuration parameters! There's the point and thanks! ;-)

**Comment by kovaccs** [comment] 2020-11-01 14:05
Done!

**Comment by yozik04** [comment] 2020-11-01 14:54
Let's keep it open until bug will be fixed.

**Comment by stosoorok** [comment] 2020-11-01 20:23
I had the time problem when I used dedicated machine with Ubuntu Server LTS and the main version of the PAI. I don't remember the PAI version number. Then I switched to KVM HassOS on Proxmox and back to main version. No problems any more. Which op sys do you have?

**Comment by kovaccs** [comment] 2020-11-02 09:27
> Which op sys do you have?

System: HassOS 4.15 (RPi4)  Core:0.117.1 
Problem temporary solved (yozik04's suggestion): SYNC_TIME: false

**Comment by LrdNrtn** [comment] 2020-11-20 10:21
I have the same issue on MG5000, but this is a fresh installation so I can't compare behavior with previous versions. 
workaround: disabled time sync temporarily

**Comment by yozik04** [comment] 2021-01-21 17:07
Somebody please test latest development release if it fixed the problem.

**Comment by kovaccs** [comment] 2021-01-21 17:51
I would test it, but there's no upgrade for Home Assitant PAI add-on!  Actual version: 2.2.4  :-O

**Comment by yozik04** [comment] 2021-01-21 18:53
I got report that it was fixed. I will try to release new version with the fix today.

**Comment by kovaccs** [comment] 2021-01-21 18:58
Thank you Jevgeni! I waiting for.  :-)

**Comment by yozik04** [comment] 2021-01-22 08:11
Released in 2.2.5

**Closed by yozik04** 2021-01-22 08:11 UTC
Labels: bug, evo192

**Comment by kovaccs** [comment] 2021-01-22 12:14
Ok! The commit is succesfull for me.  (config: SYNC_TIME: changed from false to true.)  Done!
Thank you!

**Comment by ccrisan** [comment] 2021-01-30 21:15
@yozik04 can we have this on PyPI as well?

**Comment by yozik04** [comment] 2021-01-31 19:44
Updated: https://pypi.org/project/paradox-alarm-interface/

I forgot to increment version. So some users of 2.2.4 actually got this 2.2.5 upgrade.
