### ISSUE TITLE
No idea if its important

### ISSUE THREAD

**Issue by ukrolelo** [ParadoxAlarmInterface/pai#188] opened 2020-11-04 16:40 UTC
## Alarm system
Describe your panel model EVO, access mode IP150

## Environment
HASS

## Git branch
default

## Describe the bug
2020-11-04 16:32:47,422 - INFO     - PAI.paradox.paradox - Running
2020-11-04 16:32:51,077 - ERROR    - PAI.paradox.lib.handlers - Already handled
2020-11-04 16:32:51,079 - ERROR    - PAI.paradox.lib.handlers - No handler for message 5
Detail: Container: 
    fields = Container: 
        data = b'RG\x80\x00\x00\x01\x04\x10\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 70)
        value = Container: 
            po = Container: 
                command = 5
                status = Container: 
                    reserved = False
                    alarm_reporting_pending = False
                    Winload_connected = True
                    NeWare_connected = False
            packet_length = 71
            control = Container: 
                ram_access = True
            bus_address = 0
            address = 1
            data = b'\x04\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'... (truncated, total 64)
        offset1 = 0
        offset2 = 70
        length = 70
    checksum = b'&' (total 1)

## To Reproduce
1.Just run the add-on

## Logs
No confidential stuff in logs

So i don't know if its important :-X

**Comment by ukrolelo** [comment] 2020-11-04 16:42
I'm a bit scared to test the dev version, should i please advise <3

**Comment by yozik04** [comment] 2020-11-04 16:45
Duplicate of #89
No it is fine.

Dev version will mess up homeassistant items. If master works fine for you stay on it.

**Closed** 2020-11-04 16:45 UTC
Labels: bug, to be confirmed

**Comment by ukrolelo** [comment] 2020-11-04 19:28
I would like to say big thank you!!!! For making PAI <3
I have PAI motion pir connected to HASS and whenever somebody go in bedroom i turn on circulation pump for hot water.
Its awesome <3

**Comment by yozik04** [comment] 2020-11-05 07:30
> I would like to say big thank you!!!! For making PAI <3
> I have PAI motion pir connected to HASS and whenever somebody go in bedroom i turn on circulation pump for hot water.
> Its awesome <3

I also have a circ. pump but it takes like 10 minutes to push cold water out of pipes.

**Comment by ukrolelo** [comment] 2020-11-05 07:42
> I also have a circ. pump but it takes like 10 minutes to push cold water out of pipes.

Yeah, i am now trying to do node-red automation to 30min(ON) 30min(OFF) :)
Its amazing that so many people gather around and make this Open source projects. <3

**Comment by yozik04** [comment] 2020-11-05 07:47
> > I also have a circ. pump but it takes like 10 minutes to push cold water out of pipes.
> 
> Yeah, i am now trying to do node-red automation to 30min(ON) 30min(OFF) :)
> Its amazing that so many people gather around and make this Open source projects. <3

Make an arduino/stm/esp with two temperature sensors and a relay. Difference between temperature sensors measurements would tell how much time you need to pump. You can stop pumping when temperatures will be almost the same.

**Comment by ukrolelo** [comment] 2020-11-05 08:12
> > > I also have a circ. pump but it takes like 10 minutes to push cold water out of pipes.
> > 
> > 
> > Yeah, i am now trying to do node-red automation to 30min(ON) 30min(OFF) :)
> > Its amazing that so many people gather around and make this Open source projects. <3
> 
> Make an arduino/stm/esp with two temperature sensors and a relay. Difference between temperature sensors measurements would tell how much time you need to pump. You can stop pumping when temperatures will be almost the same.

Wow, nice idea :))) <3
