### ISSUE TITLE
Arm / disarm with user code

### ISSUE THREAD

**Issue by lpaolini** [ParadoxAlarmInterface/pai#450] opened 2024-04-08 09:00 UTC
Is there any way for passing a user code when arming / disarming using the MQTT interface?
If this is possible, can anonymous arm / disarm be disabled?

**Comment by yozik04** [comment] 2024-04-08 12:18
Duplicate of #433. See there.

**Closed by yozik04** 2024-04-08 12:18 UTC
Labels: question

**Comment by yozik04** [comment] 2024-04-08 19:35
Yes, I understand that.
