### ISSUE TITLE
If running two PAI services .. possible HA entity name collision?

### ISSUE THREAD

**Issue by klvnptr** [ParadoxAlarmInterface/pai#340] opened 2023-01-02 20:47 UTC
Hello.

I'm using a two EVO192 alarm systems. I plan to run two PAI services in a docker compose each connecting to its own IP150+ module. What do I need to change in each services config file to use the same home assistant? I don't want entity name collision.

Thanks so much.

Peter

**Comment by yozik04** [comment] 2023-01-02 21:14
It is feature request. Duplicate of #329.

**Closed by yozik04** 2023-01-02 21:14 UTC
Labels: question
